spring:
  application:
    name: board-service


  datasource:
    # PostgreSQL 연결 URL (localhost:5432는 기본 포트, /뒤에는 생성한 DB 이름)
    url: jdbc:postgresql://localhost:5432/board_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # ddl-auto: update(기존 스키마 유지/변경), create(매번 새로 생성)
      ddl-auto: create
    show-sql: true # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 정렬
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL 방언 설정
